### ISSUE TITLE
Error message in log when fetching rules

### ISSUE THREAD

**Issue by phizab** [mage-one-com/qps#17]
**Describe the bug**
When fetching rules (e.g. via cronjob or manually in admin area), a HTTP status code 100 is returned. Because this code is not equal to 200, a message is logged: "Something went wrong while trying to update security rules, response: 100" and further processing of the request is stopped.

**To Reproduce**
1. Click on "Load Rules" button in admin area or execute cronjob.
2. See message in system.log file.

**Expected behavior**
The behaviour on http status code 100 should be changed, because I think this seems not to be a real error (maybe the request body is too large?). The response body contains the available rules anyway, which are not getting processed.

**Additional context**
We've installed all available patches (from MO-12 to MO-20).

**Comment by Schrank** [comment]
Hi @phizab - thanks for the issue! Will fix it.
