### ISSUE TITLE
Performance Impact?

### ISSUE THREAD

**Issue by sprankhub** [mage-one-com/qps#6]
Hooking into `controller_front_init_before` and checking various rules sounds like having potential to slow down shops. I did not look into your checks yet, but just wanted to raise this as a question: Did you test the performance impact of this - especially with **many** rules, which may be released in the future? What did you find out?

**Comment by riconeitzel** [comment]
We tested this and the impact is something between 10 to 20 ms - and: in an ideal setup this list is empty. The QPS works as an immediate mitigation tool until the patch is installed. If the patch is installed the corresponding rule is no longer requiered and this removed.
